# yfinance Options Data Pull

In [4]:
import yfinance as yf

yticker = yf.Ticker('TSLA')
yoptions = yticker.options

In [5]:
type(yticker.options)

tuple

In [7]:
for date in yoptions:
    print(date,type(date))

2022-10-07 <class 'str'>
2022-10-14 <class 'str'>
2022-10-21 <class 'str'>
2022-10-28 <class 'str'>
2022-11-04 <class 'str'>
2022-11-18 <class 'str'>
2022-12-16 <class 'str'>
2023-01-20 <class 'str'>
2023-02-17 <class 'str'>
2023-03-17 <class 'str'>
2023-04-21 <class 'str'>
2023-06-16 <class 'str'>
2023-09-15 <class 'str'>
2024-01-19 <class 'str'>
2024-03-15 <class 'str'>
2024-06-21 <class 'str'>
2025-01-17 <class 'str'>

In [9]:
yoptchain = yticker.option_chain(yoptions[5])
yoptchain

Options(calls=          contractSymbol       lastTradeDate   strike  lastPrice     bid  \
0    TSLA221118C00016670 2022-09-30 19:41:23    16.67     250.30  246.90
1    TSLA221118C00033330 2022-09-12 15:15:04    33.33     269.98  230.25
2    TSLA221118C00050000 2022-09-27 18:51:07    50.00     231.87  214.85
3    TSLA221118C00066670 2022-09-29 14:34:36    66.67     204.50  197.90
4    TSLA221118C00083330 2022-08-18 15:12:35    83.33     222.85  219.90
..                   ...                 ...      ...        ...     ...
206  TSLA221118C02200000 2022-08-24 14:04:41  2200.00       0.33    0.00
207  TSLA221118C02250000 2022-08-22 18:23:35  2250.00       0.26    0.00
208  TSLA221118C02300000 2022-08-24 17:20:01  2300.00       0.29    0.00
209  TSLA221118C02350000 2022-08-24 13:53:17  2350.00       0.35    0.00
210  TSLA221118C02400000 2022-08-24 19:07:13  2400.00       0.23    0.00

        ask    change  percentChange  volume  openInterest  impliedVolatility  \
0    250.50 -1.449997      -0.575967     1.0         104.0           3.023440
1    235.25  0.000000       0.000000     3.0         201.0           2.910159
2    216.60  0.000000       0.000000     6.0         100.0           2.140630
3    200.30  0.000000       0.000000     3.0          63.0           1.801759
4    221.45  0.000000       0.000000     NaN         165.0           5.394535
..      ...       ...            ...     ...           ...                ...
206    0.00  0.000000       0.000000     2.0         156.0           0.500005
207    0.00  0.000000       0.000000     2.0          92.0           0.500005
208    0.00  0.000000       0.000000     3.0         110.0           0.500005
209    0.00  0.000000       0.000000     1.0         316.0           0.500005
210    0.00  0.000000       0.000000   555.0        3847.0           0.500005

     inTheMoney contractSize currency
0          True      REGULAR      USD
1          True      REGULAR      USD
2          True      REGULAR      USD
3          True      REGULAR      USD
4          True      REGULAR      USD
..          ...          ...      ...
206       False      REGULAR      USD
207       False      REGULAR      USD
208       False      REGULAR      USD
209       False      REGULAR      USD
210       False      REGULAR      USD

[211 rows x 14 columns], puts=          contractSymbol       lastTradeDate   strike  lastPrice      bid  \
0    TSLA221118P00016670 2022-09-30 19:47:58    16.67       0.01     0.01
1    TSLA221118P00033330 2022-09-30 19:26:58    33.33       0.02     0.01
2    TSLA221118P00050000 2022-09-30 19:54:16    50.00       0.06     0.03
3    TSLA221118P00066670 2022-09-30 19:30:41    66.67       0.13     0.12
4    TSLA221118P00083330 2022-09-30 19:56:43    83.33       0.23     0.21
..                   ...                 ...      ...        ...      ...
198  TSLA221118P02050000 2022-08-18 14:13:41  2050.00    1141.94     0.00
199  TSLA221118P02100000 2022-08-18 14:16:41  2100.00    1191.44     0.00
200  TSLA221118P02150000 2022-08-08 17:04:01  2150.00    1257.70     0.00
201  TSLA221118P02200000 2022-03-28 14:03:39  2200.00    1150.10  1297.75
202  TSLA221118P02250000 2022-07-25 19:49:16  2250.00    1445.20  1355.70

         ask  change  percentChange  volume  openInterest  impliedVolatility  \
0       0.02    0.00       0.000000     9.0        4531.0           2.468754
1       0.03    0.00       0.000000    82.0        5411.0           1.875001
2       0.05    0.01      19.999996   108.0        3921.0           1.609377
3       0.13    0.01       8.333332    19.0        4954.0           1.500002
4       0.25   -0.01      -4.166663    22.0        2360.0           1.361331
..       ...     ...            ...     ...           ...                ...
198     0.00    0.00       0.000000    10.0           0.0           0.000010
199     0.00    0.00       0.000000     2.0           0.0           0.000010
200     0.00    0.00       0.000000    16.0           0.0           0.000010
201  1305.15    0.00       0.000000     NaN           1.0           0.000010
202  1362.20    0.00       0.000000     1.0           0.0           0.000010

     inTheMoney contractSize currency
0         False      REGULAR      USD
1         False      REGULAR      USD
2         False      REGULAR      USD
3         False      REGULAR      USD
4         False      REGULAR      USD
..          ...          ...      ...
198        True      REGULAR      USD
199        True      REGULAR      USD
200        True      REGULAR      USD
201        True      REGULAR      USD
202        True      REGULAR      USD

[203 rows x 14 columns])

In [15]:
yoptchain.calls
# yoptchain[0]

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,TSLA221118C00016670,2022-09-30 19:41:23,16.67,250.30,246.90,250.50,-1.449997,-0.575967,1.0,104.0,3.023440,True,REGULAR,USD
1,TSLA221118C00033330,2022-09-12 15:15:04,33.33,269.98,230.25,235.25,0.000000,0.000000,3.0,201.0,2.910159,True,REGULAR,USD
2,TSLA221118C00050000,2022-09-27 18:51:07,50.00,231.87,214.85,216.60,0.000000,0.000000,6.0,100.0,2.140630,True,REGULAR,USD
3,TSLA221118C00066670,2022-09-29 14:34:36,66.67,204.50,197.90,200.30,0.000000,0.000000,3.0,63.0,1.801759,True,REGULAR,USD
4,TSLA221118C00083330,2022-08-18 15:12:35,83.33,222.85,219.90,221.45,0.000000,0.000000,NaN,165.0,5.394535,True,REGULAR,USD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206,TSLA221118C02200000,2022-08-24 14:04:41,2200.00,0.33,0.00,0.00,0.000000,0.000000,2.0,156.0,0.500005,False,REGULAR,USD
207,TSLA221118C02250000,2022-08-22 18:23:35,2250.00,0.26,0.00,0.00,0.000000,0.000000,2.0,92.0,0.500005,False,REGULAR,USD
208,TSLA221118C02300000,2022-08-24 17:20:01,2300.00,0.29,0.00,0.00,0.000000,0.000000,3.0,110.0,0.500005,False,REGULAR,USD
209,TSLA221118C02350000,2022-08-24 13:53:17,2350.00,0.35,0.00,0.00,0.000000,0.000000,1.0,316.0,0.500005,False,REGULAR,USD
210,TSLA221118C02400000,2022-08-24 19:07:13,2400.00,0.23,0.00,0.00,0.000000,0.000000,555.0,3847.0,0.500005,False,REGULAR,USD

In [16]:
yoptchain.puts
# yoptchain[1]

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,TSLA221118P00016670,2022-09-30 19:47:58,16.67,0.01,0.01,0.02,0.00,0.000000,9.0,4531.0,2.468754,False,REGULAR,USD
1,TSLA221118P00033330,2022-09-30 19:26:58,33.33,0.02,0.01,0.03,0.00,0.000000,82.0,5411.0,1.875001,False,REGULAR,USD
2,TSLA221118P00050000,2022-09-30 19:54:16,50.00,0.06,0.03,0.05,0.01,19.999996,108.0,3921.0,1.609377,False,REGULAR,USD
3,TSLA221118P00066670,2022-09-30 19:30:41,66.67,0.13,0.12,0.13,0.01,8.333332,19.0,4954.0,1.500002,False,REGULAR,USD
4,TSLA221118P00083330,2022-09-30 19:56:43,83.33,0.23,0.21,0.25,-0.01,-4.166663,22.0,2360.0,1.361331,False,REGULAR,USD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198,TSLA221118P02050000,2022-08-18 14:13:41,2050.00,1141.94,0.00,0.00,0.00,0.000000,10.0,0.0,0.000010,True,REGULAR,USD
199,TSLA221118P02100000,2022-08-18 14:16:41,2100.00,1191.44,0.00,0.00,0.00,0.000000,2.0,0.0,0.000010,True,REGULAR,USD
200,TSLA221118P02150000,2022-08-08 17:04:01,2150.00,1257.70,0.00,0.00,0.00,0.000000,16.0,0.0,0.000010,True,REGULAR,USD
201,TSLA221118P02200000,2022-03-28 14:03:39,2200.00,1150.10,1297.75,1305.15,0.00,0.000000,NaN,1.0,0.000010,True,REGULAR,USD
202,TSLA221118P02250000,2022-07-25 19:49:16,2250.00,1445.20,1355.70,1362.20,0.00,0.000000,1.0,0.0,0.000010,True,REGULAR,USD